const areas = [
  {
    id: 1,
    title: 'Niederhorn',
    category: 'Bern',
    date: '29.11.2023 - 21.04.2024',
    img: '../assets/resorts/1.jpg',
    desc: 'Welcome to Niederhorn, your premier destination for winter excitement in Bern. Discover a winter wonderland with perfectly groomed slopes catering to all skill levels. Our modern facilities, family-friendly atmosphere, and après-ski delights make Niederhorn the ideal escape. Experience the thrill of skiing, snowboarding, and a variety of winter activities amidst breathtaking alpine landscapes. Join us for an unforgettable blend of adventure, relaxation, and snowy enchantment.',
  },
  {
    id: 2,
    title: 'Glacier 3000',
    category: 'Vaud',
    date: '23.11.2023 - 15.04.2024',
    img: '../assets/resorts/2.jpeg',
    desc: 'Welcome to Glacier 3000, your premier destination for winter excitement in Vaud. Discover a winter wonderland with perfectly groomed slopes catering to all skill levels. Our modern facilities, family-friendly atmosphere, and après-ski delights make Glacier 3000 the ideal escape. Experience the thrill of skiing, snowboarding, and a variety of winter activities amidst breathtaking alpine landscapes. Join us for an unforgettable blend of adventure, relaxation, and snowy enchantment.',
  },
  {
    id: 3,
    title: 'Saas-Almagell',
    category: 'Wallis',
    date: '29.11.2023 - 17.04.2024',
    img: '../assets/resorts/3.jpeg',
    desc: 'Welcome to Saas-Almagell, your premier destination for winter excitement in Wallis. Discover a winter wonderland with perfectly groomed slopes catering to all skill levels. Our modern facilities, family-friendly atmosphere, and après-ski delights make Saas-Almagell the ideal escape. Experience the thrill of skiing, snowboarding, and a variety of winter activities amidst breathtaking alpine landscapes. Join us for an unforgettable blend of adventure, relaxation, and snowy enchantment.',
  },
  {
    id: 4,
    title: 'Selital',
    category: 'Bern',
    date: '23.12.2023 - 21.04.2024',
    img: '../assets/resorts/4.jpeg',
    desc: 'Welcome to Selital, your premier destination for winter excitement in Bern. Discover a winter wonderland with perfectly groomed slopes catering to all skill levels. Our modern facilities, family-friendly atmosphere, and après-ski delights make Selital the ideal escape. Experience the thrill of skiing, snowboarding, and a variety of winter activities amidst breathtaking alpine landscapes. Join us for an unforgettable blend of adventure, relaxation, and snowy enchantment.',
  },
  {
    id: 5,
    title: 'Les Diablerets',
    category: 'Vaud',
    date: '25.11.2023 - 03.04.2024',
    img: '../assets/resorts/5.jpeg',
    desc: 'Welcome to Les Diablerets, your premier destination for winter excitement in Vaud. Discover a winter wonderland with perfectly groomed slopes catering to all skill levels. Our modern facilities, family-friendly atmosphere, and après-ski delights make Les Diablerets the ideal escape. Experience the thrill of skiing, snowboarding, and a variety of winter activities amidst breathtaking alpine landscapes. Join us for an unforgettable blend of adventure, relaxation, and snowy enchantment.',
  },
  {
    id: 6,
    title: 'Grimmialp',
    category: 'Bern',
    date: '23.11.2023 - 21.04.2024',
    img: '../assets/resorts/6.jpeg',
    desc: 'Welcome to Grimmialp, your premier destination for winter excitement in Bern. Discover a winter wonderland with perfectly groomed slopes catering to all skill levels. Our modern facilities, family-friendly atmosphere, and après-ski delights make Grimmialp the ideal escape. Experience the thrill of skiing, snowboarding, and a variety of winter activities amidst breathtaking alpine landscapes. Join us for an unforgettable blend of adventure, relaxation, and snowy enchantment.',
  },
  {
    id: 7,
    title: 'Ovronnaz',
    category: 'Wallis',
    date: '23.11.2023 - 21.04.2024',
    img: '../assets/resorts/7.jpeg',
    desc: 'Welcome to Ovronnaz, your premier destination for winter excitement in Wallis. Discover a winter wonderland with perfectly groomed slopes catering to all skill levels. Our modern facilities, family-friendly atmosphere, and après-ski delights make Ovronnaz the ideal escape. Experience the thrill of skiing, snowboarding, and a variety of winter activities amidst breathtaking alpine landscapes. Join us for an unforgettable blend of adventure, relaxation, and snowy enchantment.',
  },
  {
    id: 8,
    title: 'Moosalp',
    category: 'Wallis',
    date: '12.12.2023 - 21.03.2024',
    img: '../assets/resorts/8.jpeg',
    desc: 'Welcome to Moosalp, your premier destination for winter excitement in Wallis. Discover a winter wonderland with perfectly groomed slopes catering to all skill levels. Our modern facilities, family-friendly atmosphere, and après-ski delights make Moosalp the ideal escape. Experience the thrill of skiing, snowboarding, and a variety of winter activities amidst breathtaking alpine landscapes. Join us for an unforgettable blend of adventure, relaxation, and snowy enchantment.',
  },
  {
    id: 9,
    title: 'Charmey',
    category: 'Freiburg',
    date: '10.12.2023 - 21.03.2024',
    img: '../assets/resorts/9.jpeg',
    desc: 'Welcome to Charmey, your premier destination for winter excitement in Freiburg. Discover a winter wonderland with perfectly groomed slopes catering to all skill levels. Our modern facilities, family-friendly atmosphere, and après-ski delights make Charmey the ideal escape. Experience the thrill of skiing, snowboarding, and a variety of winter activities amidst breathtaking alpine landscapes. Join us for an unforgettable blend of adventure, relaxation, and snowy enchantment.',
  },
  {
    id: 10,
    title: 'Les Paccots',
    category: 'Freiburg',
    date: '10.12.2023 - 21.03.2024',
    img: '../assets/resorts/10.jpeg',
    desc: 'Welcome to Les Paccots, your premier destination for winter excitement in Freiburg. Discover a winter wonderland with perfectly groomed slopes catering to all skill levels. Our modern facilities, family-friendly atmosphere, and après-ski delights make Les Paccots the ideal escape. Experience the thrill of skiing, snowboarding, and a variety of winter activities amidst breathtaking alpine landscapes. Join us for an unforgettable blend of adventure, relaxation, and snowy enchantment.',
  },
  {
    id: 11,
    title: 'Riefenmatt',
    category: 'Bern',
    date: '13.12.2023 - 10.04.2024',
    img: '../assets/resorts/11.jpeg',
    desc: 'Welcome to Riefenmatt, your premier destination for winter excitement in Bern. Discover a winter wonderland with perfectly groomed slopes catering to all skill levels. Our modern facilities, family-friendly atmosphere, and après-ski delights make Riefenmatt the ideal escape. Experience the thrill of skiing, snowboarding, and a variety of winter activities amidst breathtaking alpine landscapes. Join us for an unforgettable blend of adventure, relaxation, and snowy enchantment.',
  },
  {
    id: 12,
    title: 'Les Rochers-de-Naye',
    category: 'Bern',
    date: '26.11.2023 - 10.04.2024',
    img: '../assets/resorts/12.jpeg',
    desc: 'Welcome to Les Rochers-de-Naye, your premier destination for winter excitement in Bern. Discover a winter wonderland with perfectly groomed slopes catering to all skill levels. Our modern facilities, family-friendly atmosphere, and après-ski delights make Les Rochers-de-Naye the ideal escape. Experience the thrill of skiing, snowboarding, and a variety of winter activities amidst breathtaking alpine landscapes. Join us for an unforgettable blend of adventure, relaxation, and snowy enchantment.',
  },
  {
    id: 13,
    title: 'Lauchernalp',
    category: 'Wallis',
    date: '23.11.2023 - 21.04.2024',
    img: '../assets/resorts/13.jpeg',
    desc: 'Welcome to Lauchernalp, your premier destination for winter excitement in Bern. Discover a winter wonderland with perfectly groomed slopes catering to all skill levels. Our modern facilities, family-friendly atmosphere, and après-ski delights make Lauchernalp the ideal escape. Experience the thrill of skiing, snowboarding, and a variety of winter activities amidst breathtaking alpine landscapes. Join us for an unforgettable blend of adventure, relaxation, and snowy enchantment.',
  },
  {
    id: 14,
    title: 'Schwarzsee',
    category: 'Freiburg',
    date: '23.11.2023 - 21.04.2024',
    img: '../assets/resorts/14.jpeg',
    desc: 'Welcome to Schwarzsee, your premier destination for winter excitement in Freiburg. Discover a winter wonderland with perfectly groomed slopes catering to all skill levels. Our modern facilities, family-friendly atmosphere, and après-ski delights make Schwarzsee the ideal escape. Experience the thrill of skiing, snowboarding, and a variety of winter activities amidst breathtaking alpine landscapes. Join us for an unforgettable blend of adventure, relaxation, and snowy enchantment.',
  },
  {
    id: 15,
    title: 'Springenboden',
    category: 'Bern',
    date: '23.11.2023 - 21.04.2024',
    img: '../assets/resorts/15.jpeg',
    desc: 'Welcome to Springenboden, your premier destination for winter excitement in Bern. Discover a winter wonderland with perfectly groomed slopes catering to all skill levels. Our modern facilities, family-friendly atmosphere, and après-ski delights make Springenboden the ideal escape. Experience the thrill of skiing, snowboarding, and a variety of winter activities amidst breathtaking alpine landscapes. Join us for an unforgettable blend of adventure, relaxation, and snowy enchantment.',
  },
];
